### ISSUE TITLE
QGIS doesn't sync Mergin shared project

### ISSUE THREAD

**Issue by Fahrern** [lutraconsulting/qgis-mergin-plugin#319] opened 2021-11-25 23:39 UTC
HI, 
So today after having recorded new fieldata through Mergin I wasn't able to sync the data on Qgis. As I recorded through my phone I also tried to sync the projects on Input and in that case it successfully sync.

In Qgis as soon as sync seems  completed it shows this error:

Failed to sync project  due to an unhandled exception.

Details:
Traceback (most recent call last):

  File "C:\Users/marca/USER/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 437, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 200, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

please help :)

**Comment by saberraz** [comment] 2021-11-26 06:53
Hi @Fahrern what version of QGIS do you use? And also how did you install QGIS?

Could you check the python version too?

**Comment by Fahrern** [comment] 2021-11-26 12:35
Hi, thank you for your interest in my issue.

I have installed QGIS 3.16.13 on windows. The operation was carried out
through the .exe downloaded during the update of the previous version. The
preconfigured settings have been maintained but the folder was created
within a secondary storage unit of the machine (Unit D). Not sure if this
was the  answer you were looking for.

 Python on the other hand was not yet installed on my computer. I had
downloaded the 3.9.9 and runned again the  Mergin plugin sync command but
it still shows the same error with the following details:


Traceback (most recent call last):


File
"C:\Users/marca/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py",
line 306, in pull_timer_tick

self.pull_conflicts = pull_project_finalize(self.job)


File
"C:\Users/marca/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py",
line 555, in pull_project_finalize

conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)


File
"C:\Users/marca/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py",
line 445, in apply_pull_changes

self.geodiff.make_copy_sqlite(f_conflict_file, dest)


File
"C:\Users/marca/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py",
line 221, in make_copy_sqlite

return self.clib.make_copy_sqlite(src, dst)


File
"C:\Users/marca/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py",
line 328, in make_copy_sqlite

_parse_return_code(res, "make_copy_sqlite")


File
"C:\Users/marca/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py",
line 41, in _parse_return_code

raise GeoDiffLibError(msg)


Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite.

**Comment by wonder-sk** [comment] 2021-11-26 13:19
@Fahrern would it be possible to get hold of your project folder so that we can investigate the problem further? If you could package content of the whole folder to a zip file and share it with me at martin.dobias@lutraconsulting.co.uk

**Comment by wonder-sk** [comment] 2022-01-20 14:35
Duplicate of #327

**Closed by wonder-sk** 2022-01-20 14:35 UTC
