### ISSUE TITLE
Não foi possível carregar o módulo 'Mergin' devido a um erro ao chamar o seu método initGui()erro na instalação 

### ISSUE THREAD

**Issue by Iuratsoc** [lutraconsulting/qgis-mergin-plugin#223] opened 2021-04-20 09:50 UTC
Não foi possível carregar o módulo 'Mergin' devido a um erro ao chamar o seu método initGui() 

ValueError: Invalid token type 
Traceback (most recent call last):
  File "D:/Program Files/QGIS 3.16/apps/qgis-ltr/./python\qgis\utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 90, in initGui
    self.create_manager()
  File "C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 166, in create_manager
    mc = create_mergin_client()
  File "C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 131, in create_mergin_client
    mc = MerginClient(url, auth_token, username, password, get_plugin_version())
  File "C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 51, in __init__
    token_data = decode_token_data(auth_token)
  File "C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 28, in decode_token_data
    raise ValueError("Invalid token type")
ValueError: Invalid token type

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.16.6-Hannover Hannover, bfd36fddc9 

Diretório do Python:
C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist
D:/Program Files/QGIS 3.16/apps/qgis-ltr/./python
C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Program Files/QGIS 3.16/apps/qgis-ltr/./python/plugins
D:\Program Files\QGIS 3.16\apps\Python37
D:\Program Files\QGIS 3.16\apps\Python37\Scripts
D:\Program Files\QGIS 3.16\bin\python37.zip
D:\Program Files\QGIS 3.16\apps\Python37\DLLs
D:\Program Files\QGIS 3.16\apps\Python37\lib
D:\Program Files\QGIS 3.16\bin
D:\Program Files\QGIS 3.16\apps\Python37\lib\site-packages
D:\Program Files\QGIS 3.16\apps\Python37\lib\site-packages\win32
D:\Program Files\QGIS 3.16\apps\Python37\lib\site-packages\win32\lib
D:\Program Files\QGIS 3.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Rui Manuel Costa/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by wonder-sk** [comment] 2021-04-24 08:07
Duplicate of #186

**Closed by wonder-sk** 2021-04-24 08:07 UTC
