### ISSUE TITLE
ValueError: Invalid token type

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#202] opened 2021-03-02 11:01 UTC
2021-03-02T11:14:56     WARNING    Traceback (most recent call last):
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 593, in configure
              self.mc = dlg.writeSettings()
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\configuration_dialog.py", line 88, in writeSettings
              mc = create_mergin_client()
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 116, in create_mergin_client
              return MerginClient(url, mc._auth_session['token'], username, password, get_plugin_version())
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 51, in __init__
              token_data = decode_token_data(auth_token)
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 28, in decode_token_data
              raise ValueError("Invalid token type")
             ValueError: Invalid token type

**Comment by wonder-sk** [comment] 2021-05-07 08:30
Duplicate of #186

**Closed by wonder-sk** 2021-05-07 08:30 UTC
Labels: bug
