### ISSUE TITLE
Error during downloading project

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#295] opened 2021-09-17 10:12 UTC
There is an error during downloading 'tin1/tc10_selective_sync' project

![b](https://user-images.githubusercontent.com/83582181/133766378-13b3972b-fd94-49d8-8956-fd60ea1dede9.png)

---------------------

Traceback (most recent call last):

  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/sync_dialog.py", line 138, in download_timer_tick
    download_project_finalize(self.job)

  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/mergin/client_pull.py", line 207, in download_project_finalize
    task.apply(job.directory, job.mp)

  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/mergin/client_pull.py", line 256, in apply
    file_to_merge.merge()

  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/a/python/plugins/Mergin/mergin/client_pull.py", line 493, in merge
    with open(item.download_file_path, 'rb') as chunk:

FileNotFoundError: [Errno 2] No such file or directory: '/home/jozef/Lutra/projects/a/b/tc10_selective_sync/photos_a/mergin-config.json.0'

**Comment by wonder-sk** [comment] 2021-09-17 12:35
Investigation shows that the project got broken on the server - in v14 and v18 the upload from web browser detected the change as 'rename' - something which is already disabled in the c++ and python clients, and should get disabled also in the javascript client.

I am closing this, as this is not really a plugin issue, and it is something that needs to be fixed on the server. The mergin project is broken and will need to be recreated...

**Closed by wonder-sk** 2021-09-17 12:35 UTC
Labels: bug

**Comment by wonder-sk** [comment] 2021-09-17 12:39
@jozef-budac it would be good to keep the broken project for the time being until the issue is fixed on the server
