### ISSUE TITLE
Geodiff error when creating a new Mergin project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#305] opened 2021-10-21 06:35 UTC
```
Traceback (most recent call last):

 

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 222, in push_timer_tick

    push_project_finalize(self.job)

 

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 276, in push_project_finalize

    job.mp.apply_push_changes(job.changes)

 

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 511, in apply_push_changes

    self.geodiff.make_copy_sqlite(self.fpath(path), basefile)

 

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite

    return self.clib.make_copy_sqlite(src, dst)

 

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite

    _parse_return_code(res, "make_copy_sqlite")

 

  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code

    raise GeoDiffLibError(msg)

 

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

 
```

QGIS 3.16 with the latest plugin

**Comment by wonder-sk** [comment] 2022-01-20 14:35
Duplicate of #327

**Closed by wonder-sk** 2022-01-20 14:35 UTC
Labels: bug
