### ISSUE TITLE
Can Not Delete Local Project

### ISSUE THREAD

**Issue by ismailsunni** [lutraconsulting/qgis-mergin-plugin#75] opened 2019-11-30 23:04 UTC
I got this error when I tried to remove a project locally
```
2019-12-01T00:00:34     WARNING    Traceback (most recent call last):
              File "C:/Users/ismailsunni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 128, in remove_local_project
              shutil.rmtree(self.path)
              File "C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\shutil.py", line 507, in rmtree
              return _rmtree_unsafe(path, onerror)
              File "C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\shutil.py", line 391, in _rmtree_unsafe
              onerror(os.unlink, fullname, sys.exc_info())
              File "C:\PROGRA~1\QGIS 3.10\apps\Python37\lib\shutil.py", line 389, in _rmtree_unsafe
              os.unlink(fullname)
             PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ismailsunni\\Documents\\Big files\\GeoMundus-Workshop\\Geomundus Chapter 1\\BasicFieldMapping.gpkg'
```

**Comment by ismailsunni** [comment] 2019-11-30 23:05
It turns out, the project is opened by current QGIS. Perhaps adding more friendly error message is needed

**Comment by saberraz** [comment] 2019-12-02 15:06
Duplicate of #63

**Closed by saberraz** 2019-12-02 15:06 UTC
Labels: bug
