### ISSUE TITLE
Error uploading project from the wizard

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#233] opened 2021-05-04 13:26 UTC
2021-05-04T12:12:43     WARNING    Traceback (most recent call last):
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 244, in create_new_project
              user_organisations=user_info.get("organisations", [])
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\create_project_wizard.py", line 400, in __init__
              self.package_page = PackagingPage(parent=self)
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\create_project_wizard.py", line 373, in __init__
              self.layers_view = PackageLayersTreeView()
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\create_project_wizard.py", line 353, in __init__
              self.proxy_model = LayerTreeProxyModel(self)
              File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\create_project_wizard.py", line 230, in __init__
              lid = tree_layer.layer().id()
             AttributeError: 'NoneType' object has no attribute 'id'

**Comment by wonder-sk** [comment] 2021-09-14 11:41
Duplicate of #277

**Closed by wonder-sk** 2021-09-14 11:41 UTC
Labels: bug, packaging
