### ISSUE TITLE
Plugin sync issue

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#326] opened 2022-01-18 15:30 UTC
User is having problem syncing and this is the error message:
```

File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 462, in apply_pull_changes


self.geodiff.apply_changeset(dest, server_diff)

File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 138, in apply_changeset

return self.clib.apply_changeset(base, changeset)

File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 252, in apply_changeset

_parse_return_code(res, "apply_changeset")


File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code

raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: apply_changeset

During handling of the above exception, another exception occurred:



Traceback (most recent call last):


File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick

self.pull_conflicts = pull_project_finalize(self.job)




File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize


conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)




File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 469, in apply_pull_changes

self.geodiff.make_copy_sqlite(src, dest)

File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite

return self.clib.make_copy_sqlite(src, dst)


File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite

_parse_return_code(res, "make_copy_sqlite")


File "C:\Users/isaac/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code

raise GeoDiffLibError(msg)


Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite
```

**Comment by DaleMaskeAM** [comment] 2022-01-19 09:19
I am also having an issue syncing one of my projects. The error message is slightly different.

`Traceback (most recent call last):

  File "C:\Users/Dale/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 222, in push_timer_tick
    push_project_finalize(self.job)

  File "C:\Users/Dale/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_push.py", line 267, in push_project_finalize
    server_resp_cancel = json.load(resp_cancel)

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by saberraz** [comment] 2022-01-19 09:21
Hi @DaleMaskeAM

Would it be to package your project and send it using DropBox/GoogleDrive/SharePoint to us (support@merginmaps.com)?

It will be also useful to send Diagnostic Logs (right-click on the project from the Browser panel > Diagnostic logs).

Kind regards
Saber

**Comment by DaleMaskeAM** [comment] 2022-01-19 09:42
Hi @saberraz 

I've sent through the Diagnostic Logs. I have also sent through a link for the zipped project to support@merginmaps.com.

Let me know if there is anything else I can do to assist.

Kind regards
Dale

**Comment by DaleMaskeAM** [comment] 2022-01-19 10:13
Hi @saberraz 

I've picked up that it was an error on our side. My apologies for the inconvenience and thank you very much for the support! 

Kind regards
Dale

**Comment by saberraz** [comment] 2022-01-20 10:05
Thanks Dale.

Note to devs, this ticket is still valid and is reproduced on the client's PC several times.

**Comment by wonder-sk** [comment] 2022-01-20 14:36
Duplicate of #327

**Closed by wonder-sk** 2022-01-20 14:36 UTC
Labels: bug, critical
