### ISSUE TITLE
Invalid token type

### ISSUE THREAD

**Issue by romainbh** [lutraconsulting/qgis-mergin-plugin#135] opened 2020-05-18 14:43 UTC
Install Mergin plugin in QGIS 3.10.5 x64 (W10 up to date), relaunch QGIS. Mergin seems to have an issue:

![image](https://user-images.githubusercontent.com/18001925/82225610-b784e100-9925-11ea-9d69-f6572183b53b.png)

Connect to Mergin, create a new project (blank or based on existing one), adn get this error message:

```
Une erreur est survenue lors de l'éxécution du code Python: 

ValueError: Invalid token type 
Traceback (most recent call last):
  File "C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\create_project_dialog.py", line 45, in accept_dialog
    mc = create_mergin_client()
  File "C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 94, in create_mergin_client
    mc = MerginClient(url, auth_token, username, password, get_plugin_version())
  File "C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 52, in __init__
    token_data = decode_token_data(auth_token)
  File "C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 31, in decode_token_data
    raise ValueError("Invalid token type")
ValueError: Invalid token type


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.10.5-A Coruña A Coruña, 984615fe1e 

Chemin Python :
C:/OSGEO4~1/apps/qgis-ltr/./python
C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-ltr/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/blanc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\blanc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
.
```

It happens on 15 computers in several places on Switzerland (homeworking), but not every time.

In video: https://streamable.com/5fgarq

**Comment by saberraz** [comment] 2020-05-18 16:31
One way to overcome that, is to save the password (using QGIS Auth), but there seems to be an other issue https://github.com/lutraconsulting/qgis-mergin-plugin/issues/118

**Comment by wonder-sk** [comment] 2021-05-07 08:32
Duplicate of #186

**Closed by wonder-sk** 2021-05-07 08:32 UTC
Labels: bug
