### ISSUE TITLE
Failed to sync project *** due to an unhandled exception.

### ISSUE THREAD

**Issue by maje04** [lutraconsulting/qgis-mergin-plugin#335] opened 2022-02-01 14:29 UTC
Got this error today when i tried to sync my Mergin project from QGIS. Never seen it before. The inky thing that was different was that I had a new gpkg-file in the project and then deleted it.

Traceback (most recent call last):

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 438, in apply_pull_changes
    self.geodiff.rebase(basefile, src, dest, rebase_conflicts)

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 105, in rebase
    return self.clib.rebase(base, modified_their, modified, conflict)

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 240, in rebase
    _parse_return_code(res, "rebase")

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: rebase

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 445, in apply_pull_changes
    self.geodiff.make_copy_sqlite(f_conflict_file, dest)

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:\Users/maje04/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

**Comment by alexbruy** [comment] 2022-02-17 11:39
Looks like duplicate of #327

**Closed** 2022-03-11 07:13 UTC
Labels: bug
