### ISSUE TITLE
Error syncing from QGIS (make_copy_sqlite unhandled exception)

### ISSUE THREAD

**Issue by smallPondTech** [lutraconsulting/qgis-mergin-plugin#284] opened 2021-08-12 11:18 UTC
![Screenshot 2021-08-12 061248](https://user-images.githubusercontent.com/77106891/129187568-8aea6dfa-2d6b-453b-97ba-d4fe8e93d4cf.jpg)

Traceback (most recent call last):

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 437, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 200, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 445, in apply_pull_changes
    self.geodiff.make_copy_sqlite(f_conflict_file, dest)

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:/Users/bhaeffner/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

**Comment by KerszenP24** [comment] 2021-09-02 08:06
same problem, any update?

**Comment by KerszenP24** [comment] 2021-09-02 11:05
Traceback (most recent call last):

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 461, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 200, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 306, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 555, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 469, in apply_pull_changes
    self.geodiff.make_copy_sqlite(src, dest)

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 221, in make_copy_sqlite
    return self.clib.make_copy_sqlite(src, dst)

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 328, in make_copy_sqlite
    _parse_return_code(res, "make_copy_sqlite")

  File "C:\Users/Dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: make_copy_sqlite

**Comment by KerszenP24** [comment] 2021-09-02 11:26
it should be fixed in version 2021.4.1 according to #279 
However, exact same error still occurs

**Comment by wonder-sk** [comment] 2021-09-14 09:37
It looks like the issue is that in Mergin plugin version 2021.4, the project directory got slightly broken (actually the internal .mergin sub-directory), and that's causing further errors even after upgrade to 2021.4.1. The solution at this point should be to delete the project directory and re-download the Mergin project - after that, you should stop getting these errors. We will try to issue a fix so that even broken project directory from older version of the plugin gets fixed automatically...

**Comment by wonder-sk** [comment] 2021-09-14 12:18
Related to https://github.com/lutraconsulting/mergin-py-client/issues/103

**Comment by Scherenschnitt** [comment] 2021-12-23 21:53
Had this problem with QGIS 3.10 (Coruna) and solved it by updating to current ltr 3.16.

**Comment by wonder-sk** [comment] 2022-01-20 14:35
Duplicate of #327

**Closed by wonder-sk** 2022-01-20 14:35 UTC
Labels: bug, sync
