### ISSUE TITLE
Deletes new local files when syncing

### ISSUE THREAD

**Issue by AsgerPetersen** [lutraconsulting/qgis-mergin-plugin#50] opened 2019-09-16 07:05 UTC
The plugin has deleted my project file and a mbtiles file from my local project.

The repo: https://public.cloudmergin.com/projects/AsgerPetersen/Træer I will happily share the repo with whoever may be interested.

As it can be seen from the project history, I have synced the project back and forth between desktop and phone about 10 times.

Then I added a mbtiles file to the project dir and added it as a layer to the project. Closed the project and activated mergin sync (via right click on the project under the mergin node in the browser tree). As I remember it there where no warning dialogs. After the sync my QGIS project file and my mbtiles file where both gone from my desktop!

Looking into the tracked changes on mergin, I see it was registered as a delete on mergin. I see the files mentioned here https://public.cloudmergin.com/projects/AsgerPetersen/Tr%C3%A6er/history/v12, but I cannot make any sense of what happened. It has made me wonder if I at all understand terminology of mergin and how it is supposed to work.

**Comment by saberraz** [comment] 2019-09-16 09:26
Hi @AsgerPetersen would it be possible to share the project with **saber** and **martin.varga**  on mergin please?

**Comment by AsgerPetersen** [comment] 2019-09-16 09:27
Done

**Comment by AsgerPetersen** [comment] 2019-09-16 10:43
I forgot to list the facts:

mergin-plugin: 2019.4-1
QGIS: 3.8.2
OS: OSX 10.14.6

**Comment by saberraz** [comment] 2019-09-16 15:09
From the log, the issue appears to be caused by Input. We are investigating it and let you know.

Btw, Input for iOS does not support mbtiles yet.

**Comment by saberraz** [comment] 2019-09-18 13:28
@AsgerPetersen there is a fix for this in Input. The APKs for Android are within this PR to test:
https://github.com/lutraconsulting/input/pull/466

It will be in the next release of iOS soon too.

**Closed by saberraz** 2019-09-18 13:28 UTC
Labels: bug

**Comment by AsgerPetersen** [comment] 2019-09-19 09:22
Cool. Looking forward to test the new iOS version.
